### ISSUE TITLE
I encountered an issue when I tried to upload an image that was larger than 1.5MB in size.

### ISSUE THREAD

**Issue by cigar** [sambecker/exif-photo-blog#31]
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 813522268

**Comment by sambecker** [comment]
The app should accept files up to 40mb. Would you be able to share the image that didn't work?

**Comment by sambecker** [comment]
Or, if you're able, please post the server side error log.

**Comment by sambecker** [comment]
Closing this for now—LMK if you can provide any more detail to help debug.

**Comment by cigar** [comment]
![B_2476](https://github.com/sambecker/exif-photo-blog/assets/389157/f2fb77fd-01ef-49ca-b15c-7445cb7759d3)
Hi @sambecker , could you download this image, and try to upload it to the app, and then you will see the the errors message like this below:
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 1328241451

Here is my log from the **Vercel Logs** 
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at d (/var/task/.next/server/chunks/6332.js:177:4753)
    at h (/var/task/.next/server/chunks/6332.js:177:4820)
    at g (/var/task/.next/server/chunks/9097.js:1:4254)
    at s (/var/task/.next/server/chunks/9097.js:1:5751)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async d (/var/task/.next/server/app/admin/uploads/[uploadPath]/page.js:1:5923)
