### ISSUE TITLE
I can't upload the image like this

### ISSUE THREAD

**Issue by cigar** [sambecker/exif-photo-blog#37]
![B_2476](https://github.com/sambecker/exif-photo-blog/assets/389157/f2fb77fd-01ef-49ca-b15c-7445cb7759d3)
Hi @sambecker , could you download this image, and try to upload it to the app, and then you will see the the errors message like this below:
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 1328241451

Here is my log from the **Vercel Logs** 
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at d (/var/task/.next/server/chunks/6332.js:177:4753)
    at h (/var/task/.next/server/chunks/6332.js:177:4820)
    at g (/var/task/.next/server/chunks/9097.js:1:4254)
    at s (/var/task/.next/server/chunks/9097.js:1:5751)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async d (/var/task/.next/server/app/admin/uploads/[uploadPath]/page.js:1:5923)

_Originally posted by @cigar in https://github.com/sambecker/exif-photo-blog/issues/31#issuecomment-1880330226_

**Comment by sambecker** [comment]
Thank you so much for sharing that.

There was an issue with the EXIF parser expecting numerical timestamps (and receiving a string).

Just deployed a fix. Please sync your fork and let me know if it worked!

**Comment by cigar** [comment]
Cool! the latest version is worked
