### ISSUE TITLE
I run into an issue when I change to grid view from default view

### ISSUE THREAD

**Issue by cigar** [sambecker/exif-photo-blog#40]
My site is (https://shots.cigar.design), you can have a try to preview the error message as below:

Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 534939749

Here are logs from the Vercel: **[GET] /grid**
![shots – Logs – Vercel](https://github.com/sambecker/exif-photo-blog/assets/389157/f71f910f-28a2-414b-b70e-70b85d3e9c84)

TypeError: Cannot read properties of null (reading 'replace')
    at (src/camera/index.ts:52:25)
    at (src/camera/index.ts:32:16)
    at (src/photo/PhotoGridSidebar.tsx:56:11)
    at (node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.production.min.js:42:208)
    at (node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.production.min.js:47:293)
    at (node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.production.min.js:38:228)
    at (node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.production.min.js:57:53)
    at (node_modules/.pnpm/next@14.0.4_@babel+core@7.23.7_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.production.min.js:58:128)

**Comment by sambecker** [comment]
Think I figured this out.

Can you sync your fork, then visit [/admin/configuration](https://shots.cigar.design/admin/configuration) and click "Clear Cache?"

Cache needs to be cleared because there's an updated sql query, which now requires both `make` and `model` to exist in order to recognize a photo as having a camera.

**Comment by cigar** [comment]
Nice! It worked based on your guiding me to clean the cache!

**Comment by sambecker** [comment]
Amazing! Thx for the excellent feedback + logs.
