### ISSUE TITLE
Image upload fails due to invalid time value

### ISSUE THREAD

**Issue by redac** [sambecker/exif-photo-blog#63]
Hi @sambecker! Using the latest version of the project, I'm having the same issue encountered in #37 & #31.

[Here's](https://github.com/sambecker/exif-photo-blog/assets/20306749/6b4463e6-c4b1-46e1-9492-2c35d20f7d33) the image I was trying to upload

```
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at E (/var/task/.next/server/chunks/3029.js:179:5539)
    at h (/var/task/.next/server/chunks/3029.js:179:5606)
    at m (/var/task/.next/server/chunks/8271.js:1:4300)
    at i (/var/task/.next/server/chunks/8271.js:1:5758)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async x (/var/task/.next/server/app/admin/uploads/[uploadPath]/page.js:1:4242)
``` 
Thanks a lot!

**Comment by sambecker** [comment]
Looks like that file has an empty string for the "taken at" time.

Just pushed a small update which makes the app more resilient to parsing empty strings.

Let me know if that works on your end.

Date time parsing will leverage existing behavior of using the upload time as the taken at time.
